# Generated by Django 3.1.7 on 2021-04-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
