# Generated by Django 3.1.7 on 2021-04-14 18:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000000000000), django.core.validators.MaxValueValidator(999999999999999)], verbose_name='Идентификатор транзакции')),
                ('time', models.DateTimeField()),
                ('amount', models.FloatField(verbose_name='Сумма транзакции')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_receiver', to='accounts.account', verbose_name='Получатель')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_sender', to='accounts.account', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-time'],
            },
        ),
    ]
