# Generated by Django 3.1.7 on 2021-04-09 11:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(100000000000000), django.core.validators.MaxValueValidator(999999999999999)])),
                ('datetime', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_receiver', to='transactions.transaction')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sender', to='transactions.transaction')),
            ],
        ),
    ]
