# Generated by Django 3.1.7 on 2021-04-13 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000000000000), django.core.validators.MinValueValidator(999999999999999)], verbose_name='Идентификатор транзакции')),
                ('time', models.DateTimeField()),
                ('amount', models.FloatField(verbose_name='Сумма транзакции')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_receiver', to='accounts.account', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sender', to='accounts.account', verbose_name='Отправитель')),
            ],
        ),
    ]
