# Generated by Django 3.1.7 on 2021-04-13 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210413_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000000000000), django.core.validators.MaxValueValidator(999999999999999)], verbose_name='Идентификатор транзакции'),
        ),
    ]
