# Generated by Django 3.1.7 on 2021-04-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210409_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='datetime',
            new_name='time',
        ),
    ]
